name: Knowledge Graph Weekly Update

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日UTC午夜运行
  workflow_dispatch:     # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 设置超时时间
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        cd knowledge_graph
        pip install -r requirements.txt
        
    - name: Run ClinicalTrials.gov crawler
      run: |
        cd knowledge_graph
        python crawlers/clinical_trials_gov.py
        
    - name: Run PubMed crawler
      run: |
        cd knowledge_graph
        python crawlers/pubmed_crawler.py
        
    - name: Commit updated data
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@users.noreply.github.com'
        git add knowledge_graph/data/raw/*
        git commit -m "Auto-update: KG data refresh $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
