name: 补剂知识图谱自动构建与测试

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v4
        
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt
          
      - name: 创建目录结构
        run: |
          mkdir -p data/raw data/processed
          mkdir -p images
          
      - name: 执行知识图谱构建
        run: |
          python main.py
          
      - name: 运行自动化测试
        run: |
          pytest --cov=src tests/ --cov-report=xml
          
      - name: 上传测试覆盖率
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          
      - name: 提交生成的知识图谱和图像
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动更新知识图谱"
          file_pattern: "knowledge_graph.gexf data/processed/*.csv images/*"
